### ISSUE TITLE
What does the argument "--n_samples" mean?

### ISSUE THREAD

**Issue by machanic** [theFool32/PPBA#1]
For example, if I test 1000 images to evaluate the attack success rate. Does --n_samples 1000?
Also, `u = np.zeros((N_SAMPLES, LOW_DIM))
        r = np.random.uniform(size=(N_SAMPLES, LOW_DIM))` , How to understand this?

**Comment by theFool32** [comment]
The `n_samples` means the number of samples per iteration (1 by default), not the number of images to be evaluated.
If you want to test 1000 images, please set the `testset` and `--num`.

And `np.random.uniform` is to get some random values then set `u` to `$[-\rho, 0, \rho]$` according to the values.
